#include "LevelLightScanner.h"

#include "../Formats/LevelLoader.h"
#include "../Formats/TextureAnimation.h"

#include <nlohmann/json.hpp>

#include <fstream>
#include <map>
#include <set>

namespace ALTEngine::Tools
{
    namespace
    {
        struct LevelEntry
        {
            std::string code;
            std::string sectorFolder;
            std::string mapFile;
            bool multiplayer = false;
        };

        std::vector<LevelEntry> ReadLevelList(const std::filesystem::path& manifestPath, std::string& error)
        {
            std::vector<LevelEntry> levels;

            std::ifstream file(manifestPath);
            if (!file)
            {
                error = "could not open " + manifestPath.string();
                return levels;
            }

            nlohmann::json root;
            try { file >> root; }
            catch (const std::exception& e)
            {
                error = std::string("malformed LevelManifest.json: ") + e.what();
                return levels;
            }

            for (const auto& chapter : root.value("chapters", nlohmann::json::array()))
            {
                for (const auto& part : chapter.value("parts", nlohmann::json::array()))
                {
                    std::string sector = part.value("sectorFolder", "");
                    for (const auto& level : part.value("levels", nlohmann::json::array()))
                    {
                        levels.push_back({ level.value("code", ""), sector, level.value("mapFile", ""), false });
                    }
                }
            }

            if (root.contains("multiplayer"))
            {
                const auto& mp = root["multiplayer"];
                std::string sector = mp.value("sectorFolder", "");
                for (const auto& level : mp.value("levels", nlohmann::json::array()))
                {
                    levels.push_back({ level.value("code", ""), sector, level.value("mapFile", ""), true });
                }
            }

            return levels;
        }

        const char* ModeName(int mode)
        {
            switch (mode)
            {
            case 0: return "static";
            case 1: return "blink";
            case 3: return "blinkAlt";
            case 4: return "gouraud";
            default: return "unknown";
            }
        }
    }

    ScanResult ScanAllLevelsForLights(const std::filesystem::path& cdDirectory,
                                      const std::filesystem::path& manifestPath,
                                      const std::filesystem::path& outputPath)
    {
        ScanResult result;

        std::string error;
        std::vector<LevelEntry> levels = ReadLevelList(manifestPath, error);
        if (!error.empty())
        {
            result.message = error;
            return result;
        }
        if (levels.empty())
        {
            result.message = "LevelManifest.json listed no levels";
            return result;
        }

        nlohmann::json out;
        out["_note"] =
            "Generated by LevelLightScanner - a catalogue of every level face carrying a light or an "
            "animation. Faces are identified by their vertex indices because face numbering is not "
            "stable. `drawRoutine` is the on-disk +0x12 byte; routine 8 means texIndex is an ANIMATOR "
            "ORDINAL rather than a texture descriptor. `lightId` is the on-disk +0x13 byte's low 7 "
            "bits. Only faces that are animated or whose light record is non-static are listed - "
            "ordinary static faces need nothing beyond the light index their geometry already "
            "carries. A replacement may define MORE faces than are listed here; nothing depends on "
            "the counts.";
        out["levels"] = nlohmann::json::array();

        for (const LevelEntry& entry : levels)
        {
            std::filesystem::path mapPath = cdDirectory / entry.sectorFolder / entry.mapFile;

            std::error_code ec;
            if (!std::filesystem::is_regular_file(mapPath, ec))
            {
                result.levelsMissing++;
                continue;
            }

            ALTEngine::Formats::LevelGeometry level;
            try { level = ALTEngine::Formats::LevelLoader::Load(mapPath); }
            catch (const std::exception& e)
            {
                nlohmann::json bad;
                bad["code"] = entry.code;
                bad["mapFile"] = entry.mapFile;
                bad["error"] = e.what();
                out["levels"].push_back(bad);
                result.levelsMissing++;
                continue;
            }

            ALTEngine::Formats::TextureAnimator animator;
            animator.Reset(level);

            nlohmann::json levelJson;
            levelJson["code"] = entry.code;
            levelJson["sectorFolder"] = entry.sectorFolder;
            levelJson["mapFile"] = entry.mapFile;
            levelJson["multiplayer"] = entry.multiplayer;
            levelJson["quadCount"] = level.quads.size();
            levelJson["vertexCount"] = level.vertices.size();

            // Light record census, so a replacement author can see what modes a
            // level actually uses without loading it themselves.
            std::map<int, int> modeCensus;
            for (const ALTEngine::Formats::LightRecord& record : level.lights)
            {
                modeCensus[record.mode]++;
            }
            nlohmann::json census = nlohmann::json::object();
            for (const auto& [mode, count] : modeCensus)
            {
                census[ModeName(mode)] = count;
            }
            levelJson["lightRecordModes"] = census;

            // Animators, with the frames each one outputs. Duplicated listIds
            // are normal and meaningful: one animator instance per face that
            // needs independent state.
            nlohmann::json animators = nlohmann::json::array();
            for (size_t i = 0; i < animator.Count(); ++i)
            {
                const auto& a = animator.Animators()[i];
                nlohmann::json aj;
                aj["ordinal"] = i;
                aj["listId"] = a.listId;
                aj["variant"] = a.variant;
                aj["variantMax"] = a.variantMax;
                aj["armedOnLoad"] = (a.variant >= a.variantMax);
                uint16_t first = 0;
                aj["firstOutputTexIndex"] = animator.CurrentTexture(static_cast<int>(i), first) ? first : -1;
                animators.push_back(aj);
            }
            levelJson["animators"] = animators;

            // The faces themselves, GROUPED by their light/animation
            // signature rather than listed one object per face. A level can
            // have thousands of qualifying faces and repeating the key names
            // for every one of them made the manifest tens of megabytes; the
            // signature is what a replacement actually needs, and the vertex
            // quads under it are just data.
            struct Signature
            {
                int lightId;
                int mode;
                int drawRoutine;
                int animatorOrdinal; // -1 when not animated

                bool operator<(const Signature& o) const
                {
                    if (lightId != o.lightId) { return lightId < o.lightId; }
                    if (mode != o.mode) { return mode < o.mode; }
                    if (drawRoutine != o.drawRoutine) { return drawRoutine < o.drawRoutine; }
                    return animatorOrdinal < o.animatorOrdinal;
                }
            };

            std::map<Signature, std::vector<const ALTEngine::Formats::ModelQuad*>> grouped;
            int animatedCount = 0, nonStaticLitCount = 0;

            for (const ALTEngine::Formats::ModelQuad& quad : level.quads)
            {
                int lightId = quad.reserved & 0x7f;
                bool animated = (quad.flags == ALTEngine::Formats::DRAW_ROUTINE_ANIMATED);

                int mode = -1;
                if (lightId < static_cast<int>(level.lights.size()))
                {
                    mode = level.lights[static_cast<size_t>(lightId)].mode;
                }

                if (!animated && mode <= 0) { continue; }

                if (animated) { animatedCount++; }
                if (mode > 0) { nonStaticLitCount++; }

                Signature key{ lightId, mode, quad.flags, animated ? static_cast<int>(quad.texIndex) : -1 };
                grouped[key].push_back(&quad);
            }

            nlohmann::json groups = nlohmann::json::array();
            for (const auto& [key, quads] : grouped)
            {
                nlohmann::json g;
                g["lightId"] = key.lightId;
                if (key.mode >= 0)
                {
                    g["lightMode"] = ModeName(key.mode);
                    if (std::string(ModeName(key.mode)) == "unknown") { g["lightModeRaw"] = key.mode; }
                }
                g["drawRoutine"] = key.drawRoutine;
                if (key.animatorOrdinal >= 0)
                {
                    g["animatorOrdinal"] = key.animatorOrdinal;
                    g["animatorInRange"] = static_cast<size_t>(key.animatorOrdinal) < animator.Count();
                }
                g["faceCount"] = quads.size();

                nlohmann::json faceList = nlohmann::json::array();
                for (const ALTEngine::Formats::ModelQuad* quad : quads)
                {
                    // Vertex quad only - the stable identifier. d is -1 for a
                    // triangle.
                    faceList.push_back({ quad->a, quad->b, quad->c, quad->d });
                }
                g["faces"] = faceList;
                groups.push_back(g);
            }

            levelJson["catalogued"] = {
                { "faces", [&]{ size_t n = 0; for (const auto& [k, v] : grouped) { (void)k; n += v.size(); } return n; }() },
                { "animatedFaces", animatedCount },
                { "groups", groups.size() }
            };
            levelJson["faceGroups"] = groups;

            out["levels"].push_back(levelJson);
            result.levelsScanned++;
            for (const auto& [key, quads] : grouped) { (void)key; result.facesRecorded += static_cast<int>(quads.size()); }
        }

        std::error_code ec;
        std::filesystem::create_directories(outputPath.parent_path(), ec);

        std::ofstream file(outputPath);
        if (!file)
        {
            result.message = "could not write " + outputPath.string();
            return result;
        }
        // Indented: this is read by people replacing level models, not just by
        // code. See OVERRIDE/LightManifestExample.json for the annotated form.
        file << out.dump(2);

        result.ok = true;
        result.message = "scanned " + std::to_string(result.levelsScanned) + " level(s), "
                       + std::to_string(result.levelsMissing) + " missing, "
                       + std::to_string(result.facesRecorded) + " face(s) recorded -> "
                       + outputPath.string();
        return result;
    }
}
